### ISSUE TITLE
Make log files more accessible

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/ocdsdata#2]
The API is disabled by default: https://airflow.apache.org/docs/apache-airflow/stable/security/api.html

I think a user with a Public or Viewer role would also need to be created: https://airflow.apache.org/docs/apache-airflow/stable/security/access-control.html

This would make it possible to query the logs of different steps, without web scraping.

Example authentication failure: https://ocdsdata.opendataservices.coop/api/v1/dags/uk_contracts_finder

Relevant queries:

* List DAGs: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dags
* List DAG runs: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_runs
* From there, we have the values needed to retrieve log files for tasks of interest, for example: https://ocdsdata.opendataservices.coop/get_logs_with_metadata?dag_id=uk_contracts_finder&task_id=compile_releases&execution_date=2021-04-09T00%3A00%3A00%2B00%3A00&try_number=1&metadata=null

**Comment by kindly** [comment]
@jpmckinney Thanks, something to make the logs more accessible and persisted is a good idea.

I think I would prefer to go with a slightly different approach and to copy the logs to the public s3 bucket . There is a remote logging option that may work for this http://airflow.apache.org/docs/apache-airflow/1.10.2/howto/write-logs.html#writing-logs-to-amazon-s3

The stats collection could work out how to link a source to the logs so you could look at the stat json to find the url of the log text file for each stage.  Not exactly an API but better than scraping the page (which is hard as the logs are loaded with javascript)  

My aim is to make the airflow instance such that if it goes down then nothing will happen apart from the data getting a bit old, so making the API anything to rely on worries me.  This is why I have resisted linking back to the logs from the static website so far.

**Comment by jpmckinney** [comment]
Sounds good to me! I've changed the issue title.

**Comment by kindly** [comment]
Logs are now in the object storage and get moved there after each job has finished.

@jpmckinney  For the purpose of easily getting access to all the log files the collection stats now makes a JSON file that indexes where all the log files are for easier access:

https://fra1.digitaloceanspaces.com/ocdsdata/metadata/logs.json

Also now the website has links to latest log files too.

![image](https://user-images.githubusercontent.com/30636/117549345-d1856b00-b031-11eb-9af9-5e0ab39ee819.png)

**Comment by jpmckinney** [comment]
Awesome, thanks!
