### ISSUE TITLE
SQLite: Use NULL instead of empty string

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/ocdsdata#7]
According to https://ocds-downloads.opendata.coop/source/uk_fts#table-parties, `parties` has 31,319 rows and the field usage count for `identifier_id` is 2,042.

I would expect `identifier_id` to be NULL in the rows for which it is not available, but it appears to be a blank string:

```sql
select
  identifier_id is null,
  identifier_id = '',
  count(*)
from
  parties
group by
  identifier_id is null,
  identifier_id = '';
```

index | identifier_id is null | identifier_id = &amp;#39;&amp;#39; | count(*)
-- | -- | -- | --
0 | 0 | 0 | 2042
1 | 0 | 1 | 29277

[Notebook](https://colab.research.google.com/drive/1d1bGuvT_T1gvYmzapBSfrrjhhw14F--F?usp=sharing)

**Comment by jpmckinney** [comment]
Typically it's better to use a single value to represent "no value", and for strings it makes more sense for this to be the empty string rather than NULL. Otherwise, you need to check for both empty string and NULL to be sure you have matched all the "no value" rows.

**Comment by duncandewhurst** [comment]
Makes sense. This must have tripped me up somewhere, but I don't remember where.
